### ISSUE TITLE
Problem with Object rendering 

### ISSUE THREAD

**Issue by sivaramr** [django-nonrel/django-nonrel#14]
views.py

def where(request):
    user=request.user
    try:
        report = Report.objects.get(user=user.id)
    except:
        report = None
    reporttype = ReportType.objects.all()
    return render(request, 'incident/where.html',
        {
            'newreport_menu': True,
            'reporttype':reporttype
    })

models.py

class ReportType(models.Model):
   report = models.ForeignKey(Report)
    title = models.CharField('Incident Type', max_length=200)

```
def __unicode__(self):
    return self.title
```

Consider,in title field two values namely Classroom and Playground are their,in my page it is rendered as like this [<ReportType: Classroom>, <ReportType: Playground>] ,so i dont want to display the ReportType.What would be the problem.

Thanks

**Comment by aburgel** [comment]
@sivaramr, github issues is for posting bugs and feature requests for the project, not for support questions.

you're better off posting either to the nonrel mailing list or the django-users mailing list, in this case i think django-users would be better because your trouble seems to be with django and not with any nonrel specific issue.
